### ISSUE TITLE
Minor issues

### ISSUE THREAD

**Issue by f6cnb** [hamnetdb/hamnetdb#1]
Hi, 
When you use a /31 subnet, the sites do not show correctly in 
http://hamnetdb.net/?m=as&q=&as=64745&tab=&osm=1
There are 3 sites in the subnet section instead of 2
73 Remi F6CNB/N5CNB

**Comment by oe2lsp** [comment]
Hi Remi,
tnx for your report.
You are correct, if there is a /31 network and the IP after this network belongs to a different site this problem occur. (often but not all always )
We 'll add it to our list and fix it as soon as possible.
73 Lucas OE2LSP

**Comment by oe2lsp** [comment]
Hi Remi,
should be solved with the newest update.
73 Lucas OE2LSP
